[General]
network = MM1
sim-time-limit = 200000s
repeat = 10

# Service (1/µ = 12s)
**.serviceMean = 12s


############################################################
#          CONFIGURATIONS LAMBDA (TABLE STATIQUE)          
############################################################

# -------- λ = 1/4 = 0.25  --------
[Config lambda4]
extends = General
GEN.meanInterArrival = 4s


# -------- λ = 1/8 = 0.125 --------
[Config lambda8]
extends = General
GEN.meanInterArrival = 8s


# -------- λ = 1/12 ≈ 0.083 --------
[Config lambda12]
extends = General
GEN.meanInterArrival = 12s


# -------- λ = 1/16 = 0.0625 --------
[Config lambda16]
extends = General
GEN.meanInterArrival = 16s


# -------- λ = 1/20 = 0.05 --------
[Config lambda20]
extends = General
GEN.meanInterArrival = 20s
